version: '3'
services:
  bungeecord:
    restart: always
    image: openjdk:17-slim-bullseye
    volumes:
      - ./bungeecord:/mc
    working_dir: /mc
    command: ["java",  "-Xms2G","-Xmx2G","-jar", "/mc/BungeeCord.jar","nogui"]
    ports:
      - 25565:25565
      - 19132:19132/udp
  mc1:
    restart: always
    image: openjdk:17-slim-bullseye
    volumes:
      - ./mc:/mc
    working_dir: /mc
    command: ["java",  "-Xms3G","-Xmx3G","-jar", "/mc/paper-1.20.4-378.jar","nogui"]
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./backup-volume-db:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: thisismariadb
    ports:
      - 3306:3306



